development:
  adapter: mysql2
  encoding: utf8
  database: insulation_unlimited
  username: root
  password: saints637
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: insulation_unlimited_test
  pool: 5
  username: root
  password: saints637
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: insulation_unlimited
  username: root
  password: saints637
  host: localhost
